# Generated by Django 5.2.3 on 2025-06-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miners', '__first__'),
        ('stakes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=10)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miners.miner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('unlock_time', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('stake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakes.stake')),
            ],
        ),
    ]
