# Generated by Django 4.2.6 on 2025-07-11 22:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='reward_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.5'), max_digits=5),
        ),
    ]
