# Generated by Django 4.2.6 on 2025-07-30 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_rewardcycle_reward_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcycle',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30),
        ),
    ]
