# Generated by Django 4.2.6 on 2025-07-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.CharField(max_length=255)),
                ('gas_limit', models.PositiveIntegerField(default=21000)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='token_app.token')),
            ],
        ),
    ]
