# Generated by Django 5.2.3 on 2025-06-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miners', '__first__'),
        ('token_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='miners.miner')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_app.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
