# Generated by Django 4.2.6 on 2025-07-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0004_alter_miner_options_alter_userminer_options'),
        ('token_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stake',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stake', 'verbose_name_plural': 'Stakes'},
        ),
        migrations.AlterField(
            model_name='stake',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='stake',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stake',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='miners.miner', verbose_name='Miner'),
        ),
        migrations.AlterField(
            model_name='stake',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_app.token', verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='stake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
