# Generated by Django 4.2.6 on 2025-08-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_token_contract_address_token_decimals_tokensettings'),
        ('stakes', '0002_alter_stake_options_alter_stake_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='token_app.token', verbose_name='Token'),
        ),
    ]
