# Generated by Django 4.2.6 on 2025-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
