# Generated by Django 4.2.6 on 2025-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_contactinfo_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='about_us_text',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='about_us',
            field=models.TextField(blank=True, help_text='Write a description about your company or platform', null=True, verbose_name='About Us Text'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(help_text='Enter your office or company address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(help_text='Enter support contact email', max_length=254, verbose_name='Support Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='support_phone',
            field=models.CharField(help_text='Enter the support phone number', max_length=30, verbose_name='Support Phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
