# Generated by Django 4.2.6 on 2025-07-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
