# Generated by Django 4.2.6 on 2025-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='otp_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
