# Generated by Django 4.2.6 on 2025-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailverification_otp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
