# Generated by Django 4.2.6 on 2025-07-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('level', models.PositiveIntegerField(verbose_name='Level')),
                ('power', models.FloatField(verbose_name='Power')),
                ('price', models.FloatField(verbose_name='Price')),
                ('image', models.ImageField(blank=True, help_text='Upload an image representing this plan', null=True, upload_to='plans/', verbose_name='Plan Image')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='token_app.token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['level', 'name'],
            },
        ),
    ]
