# Generated by Django 4.2.6 on 2025-07-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20250711_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_reward_percent',
            field=models.DecimalField(decimal_places=2, default=4.5, help_text='درصد سود ماهانه به صورت درصد (مثلاً 4.5)', max_digits=5),
        ),
    ]
