# Generated by Django 4.2.6 on 2025-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_token_contract_address_token_decimals_tokensettings'),
        ('plans', '0006_plan_monthly_reward_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='token',
        ),
        migrations.AddField(
            model_name='plan',
            name='tokens',
            field=models.ManyToManyField(related_name='plans', to='token_app.token', verbose_name='Tokens'),
        ),
    ]
