# Generated by Django 4.2.6 on 2025-07-06 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakes', '0002_alter_stake_options_alter_stake_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('stake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rewards', to='stakes.stake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
