# Generated by Django 4.2.6 on 2025-07-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_token_contract_address_token_decimals_tokensettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0003_walletauthnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreward',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='token_app.token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
