# Generated by Django 4.2.6 on 2025-07-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_alter_rewardcycle_amount'),
        ('wallets', '0004_pendingreward_token_alter_walletconnection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreward',
            name='reward_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.rewardcycle'),
        ),
    ]
