# Generated by Django 4.2.6 on 2025-08-08 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakes', '0003_alter_stake_token'),
        ('reward', '0003_alter_rewardcycle_amount'),
        ('wallets', '0005_pendingreward_reward_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreward',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingreward',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pendingreward',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('claimed', 'Claimed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='pendingreward',
            unique_together={('user', 'stake', 'reward_cycle')},
        ),
    ]
