# Generated by Django 4.2.6 on 2025-09-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_outgoingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreward',
            name='withdraw_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_rewards', to='wallets.outgoingtransaction'),
        ),
        migrations.AddField(
            model_name='pendingreward',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingreward',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
    ]
