# Generated by Django 4.2.6 on 2025-09-10 23:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_pendingreward_withdraw_tx_pendingreward_withdrawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_amount', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outgoing_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallets.outgoingtransaction')),
                ('pending_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_items', to='wallets.pendingreward')),
            ],
            options={
                'indexes': [models.Index(fields=['outgoing_tx'], name='wallets_wit_outgoin_0fbfa4_idx'), models.Index(fields=['pending_reward'], name='wallets_wit_pending_fda62e_idx')],
            },
        ),
    ]
