# Generated by Django 4.2.6 on 2025-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_withdrawalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('next_nonce', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='destination_address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
