# Generated by Django 5.2.3 on 2025-06-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0002_alter_miner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='user',
        ),
    ]
