# Generated by Django 4.2.6 on 2025-07-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0003_remove_miner_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Miner', 'verbose_name_plural': 'Miners'},
        ),
        migrations.AlterModelOptions(
            name='userminer',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Miner', 'verbose_name_plural': 'User Miners'},
        ),
    ]
