# Generated by Django 4.2.6 on 2025-07-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
        ('miners', '0009_alter_miner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userminer',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='token_app.token'),
        ),
    ]
