# Generated by Django 4.2.6 on 2025-07-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0010_userminer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='user',
        ),
    ]
