# Generated by Django 4.2.6 on 2025-07-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0007_auto_20250711_0417'),
        ('miners', '0011_remove_miner_user'),
    ]

    operations = [
    ]
