# Generated by Django 4.2.6 on 2025-08-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_token_contract_address_token_decimals_tokensettings'),
        ('miners', '0012_merge_0007_auto_20250711_0417_0011_remove_miner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='token',
        ),
        migrations.AddField(
            model_name='miner',
            name='tokens',
            field=models.ManyToManyField(related_name='miners', to='token_app.token'),
        ),
    ]
